server:
  port: 8003
spring:
  application:
    name: blog-chat-room
  datasource:
    username: root
    password: 3307yun3306
    url: jdbc:mysql://124.222.111.81:3307/room?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.111.81:8850

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto